- task-launcher/src/tasks/mental-rotation/timeline.js
- task-launcher/src/tasks/mental-rotation/trials/instructions.js
added instructions and prolific link for adult pilot
> add prolific mental rotation instructions and finish

- task-launcher/src/styles/task.scss
- task-launcher/src/tasks/mental-rotation/timeline.js
- task-launcher/src/tasks/mental-rotation/trials/instructions.js
- task-launcher/src/tasks/shared/helpers/getStimulus.js
- task-launcher/src/tasks/shared/trials/afcStimulus.js
Adding instruction video for mental-rotation and disallowing up/down arrowkeys for 2afc
> MR Instruction video and 2afc change

- task-launcher/package.json
- task-launcher/serve/serve.js
- task-launcher/src/index.js
- task-launcher/src/tasks/mental-rotation/trials/instructions.js
- task-launcher/src/tasks/same-different-selection/trials/stimulus.js
- task-launcher/src/tasks/shared/helpers/getTranslations.js
- task-launcher/src/tasks/shared/helpers/initConfig.js
- task-launcher/src/tasks/shared/helpers/initTimeline.js
- Changing translations parsing logic to account for some edge cases
- Changing pid to be read from store not serve.js (Was causing an error on the dashboard)
- Removing unused imports
> Revamping logic for pulling translations from CSV

- task-launcher/src/tasks/shared/helpers/fetchAndParseCorpus.js
- task-launcher/src/tasks/shared/helpers/initTrialSaving.js
- task-launcher/src/tasks/shared/trials/afcStimulus.js
> Saving trials if flag turned on after a trial is finished

- task-launcher/src/tasks/hearts-and-flowers/helpers/utils.js
- task-launcher/src/tasks/hearts-and-flowers/trials/fixation.js
- task-launcher/src/tasks/hearts-and-flowers/trials/instructions.js
- task-launcher/src/tasks/hearts-and-flowers/trials/practice.js
Keep on fixing the keyboard input.
Apologies the last commit of PR #69 (commit [8ca8e84](https://github.com/levante-framework/core-tasks/pull/69/commits/8ca8e843368a0ef3013d7710f76f2d0e037bcf80)) should have been the first commit here.
> HaF: keep on fixing keyboard input

- task-launcher/src/tasks/hearts-and-flowers/helpers/utils.js
- task-launcher/src/tasks/hearts-and-flowers/trials/fixation.js
- task-launcher/src/tasks/hearts-and-flowers/trials/instructions.js
- task-launcher/src/tasks/hearts-and-flowers/trials/practice.js
- task-launcher/src/tasks/hearts-and-flowers/trials/stimulus.js
We're disabling input keyboard on touchscreens and expecting spacebar/enter key for advancing through instruction screens.
> HaF keyboard input

- task-launcher/serve/serve.js
- task-launcher/src/tasks/math/timeline.js
- task-launcher/src/tasks/math/trials/sliderStimulus.js
- task-launcher/src/tasks/matrix-reasoning/timeline.js
- task-launcher/src/tasks/mental-rotation/timeline.js
- task-launcher/src/tasks/same-different-selection/trials/afcMatch.js
- task-launcher/src/tasks/same-different-selection/trials/stimulus.js
- task-launcher/src/tasks/shared/helpers/fetchAndParseCorpus.js
- task-launcher/src/tasks/shared/helpers/fractionToMathML.js
- task-launcher/src/tasks/shared/trials/afcStimulus.js
- task-launcher/src/tasks/theory-of-mind/timeline.js
- task-launcher/src/tasks/trog/timeline.js
should test a little more.
tempted to also remove 
`afcCondtional()` from afcStimulus.js (it's unused anywhere -- what is/was it for?), and merge `afcStimulus()` with `afcStimulusWithTimeoutCondition()` -- any reason not to?
> Hide keyhelpers and add maxtime condition

- task-launcher/src/styles/task.scss
- task-launcher/src/tasks/math/timeline.js
- task-launcher/src/tasks/math/trials/sliderStimulus.js
- task-launcher/src/tasks/shared/helpers/setSkipCurrentBlock.js
And removing `console.log` statements
> Increasing the replay button size

- task-launcher/src/tasks/math/trials/sliderStimulus.js
- task-launcher/src/tasks/same-different-selection/trials/afcMatch.js
- task-launcher/src/tasks/shared/helpers/initTrialSaving.js
addresses a few tickets:
https://www.notion.so/Save-trialIndex-property-and-all-required-fields-with-trial-data-140ecedcade646f28793eb09f543da3c?pvs=4
https://www.notion.so/same-different-selection-expected_answer-is-No-answer-provided-and-is_correct-is-TRUE-9420dca0f20f483697d4f740422e8a64?pvs=4
https://www.notion.so/corpusTrialType-is-missing-for-number-line-trials-9a3ccd14e5b44d989fc38dc63160eace?pvs=4
> Save trial index property and all required fields with trial data

- task-launcher/src/styles/abstracts/_index.scss
- task-launcher/src/styles/abstracts/_spacings.scss
- task-launcher/src/styles/layout/_containers.scss
- task-launcher/src/styles/pages/_haf.scss
- task-launcher/src/styles/task.scss
- task-launcher/src/tasks/hearts-and-flowers/helpers/utils.js
- task-launcher/src/tasks/hearts-and-flowers/trials/fixation.js
- task-launcher/src/tasks/hearts-and-flowers/trials/instructions.js
- task-launcher/src/tasks/hearts-and-flowers/trials/practice.js
- task-launcher/src/tasks/hearts-and-flowers/trials/stimulus.js
- task-launcher/src/tasks/shared/trials/fullScreen.js
This uses the new styling convention to refactor the hearts and flowers task.
> Hearts and Flowers styling refactor

- task-launcher/src/tasks/hearts-and-flowers/trials/instructions.js
- task-launcher/src/tasks/math/trials/instructions.js
- task-launcher/src/tasks/matrix-reasoning/trials/instructions.js
- task-launcher/src/tasks/mental-rotation/trials/instructions.js
- fixed H&F, math, matrix, and mental rotation
> don't allow keyboard responses on instructions

- task-launcher/src/tasks/shared/trials/afcStimulus.js
1. Now keyboard and mouse click effectively call the same function
2. Should work with 2 choices and 4 choices
I have only tested it with egma-math with keyhelpers so far. But it might be worth testing other tasks.
> Consolidate practice button click logic

- task-launcher/src/tasks/matrix-reasoning/timeline.js
- task-launcher/src/tasks/shared/trials/afcStimulus.js
Added the neutral 'select' audio to the response buttons and removed the audio prompts after the practice trials.
> Matrix reasoning button audio

- task-launcher/src/tasks/shared/trials/afcStimulus.js
This implementation:
1. Does not stop the animation if either image assets or audio assets are missing for the staggered animation
2. It will just play null audio and move on with the animation
> Graceful handling of missing assets during staggered assets

- task-launcher/src/tasks/matrix-reasoning/timeline.js
- task-launcher/src/tasks/shared/trials/afcStimulus.js
This should include all the changes required to stop the matrix reasoning audio feedback after 3 trials.
> Update matrix reasoning audio prompts

- task-launcher/src/tasks/intro/trials/instructions.js
- task-launcher/src/tasks/memory-game/timeline.js
- task-launcher/src/tasks/memory-game/trials/instructions.js
- task-launcher/src/tasks/same-different-selection/timeline.js
- task-launcher/src/tasks/same-different-selection/trials/stimulus.js
- task-launcher/src/tasks/shared/trials/feedback.js
1. Some small button style update
2. Parameters on feedback component
3. Audio replay ends when trial ends for intro task to prevent overlap
> Parameterizing the feedback component

- task-launcher/src/styles/abstracts/_spacings.scss
- task-launcher/src/styles/abstracts/_variables.scss
- task-launcher/src/styles/components/_buttons.scss
- task-launcher/src/tasks/shared/trials/afcStimulus.js
I created a new image-medium class that is larger than the standard one (hopefully without causing the buttons to go out of screen).
> Making the vocab and TROG buttons larger

- task-launcher/src/tasks/matrix-reasoning/helpers/config.ts
- task-launcher/src/tasks/mental-rotation/helpers/config.ts
- task-launcher/src/tasks/shared/helpers/prepareChoices.js
- task-launcher/src/tasks/shared/trials/afcStimulus.js
- task-launcher/src/tasks/theory-of-mind/helpers/config.ts
- task-launcher/src/tasks/trog/helpers/config.ts
- task-launcher/src/tasks/vocab/helpers/config.ts
- task-launcher/types/index.d.ts
There were issues with the introduction of layoutconfig and also there was most likely a previous issue with race condition of keyResponseMap. This PR attempts to fix both of them.
> Fixing both button response and click response

- task-launcher/src/tasks/matrix-reasoning/helpers/config.ts
- task-launcher/src/tasks/shared/helpers/config.ts
- task-launcher/src/tasks/shared/helpers/validateLayoutConfig.ts
- task-launcher/src/tasks/shared/trials/afcStimulus.ts
- task-launcher/types/index.d.ts
Renames the noAudio parameter in LayoutConfig to playAudioOnLoad
> Rename noAudio to playAudioOnLoad

- task-launcher/src/tasks/matrix-reasoning/timeline.ts
- task-launcher/src/tasks/mental-rotation/timeline.ts
- task-launcher/src/tasks/shared/trials/repeatInstructions.ts
- task-launcher/src/tasks/shared/trials/repeatInstructionsMessage.js
Repeats the instructions if the first two answers to real trials are incorrect. I think it might make sense to add a simple screen (just text + audio) that says something like "Let's review the instructions!" before they are repeated  - I can create that if it sounds good.
> Repeat instructions after two incorrect answers in a row

- task-launcher/src/tasks/hearts-and-flowers/trials/stimulus.js
- task-launcher/src/tasks/math/trials/sliderStimulus.ts
- task-launcher/src/tasks/memory-game/trials/stimulus.js
- task-launcher/src/tasks/same-different-selection/trials/afcMatch.ts
- task-launcher/src/tasks/same-different-selection/trials/stimulus.ts
- task-launcher/src/tasks/shared/trials/afcStimulus.ts
Saves response location as an index (0-3 if there are 4 buttons) for all tasks.
> log response location for all tasks

- task-launcher/src/tasks/hearts-and-flowers/trials/instructions.js
- task-launcher/src/tasks/hearts-and-flowers/trials/practice.js
- task-launcher/src/tasks/hearts-and-flowers/trials/stimulus.js
- task-launcher/src/tasks/intro/trials/instructions.ts
- task-launcher/src/tasks/matrix-reasoning/trials/instructions.ts
- task-launcher/src/tasks/memory-game/trials/instructions.ts
- task-launcher/src/tasks/memory-game/trials/stimulus.ts
- task-launcher/src/tasks/taskSetup.js
Adds a new field to memory game data called trialMode (either 'input' or 'display'). Also should cover all of the cases where assessment_stage was not being saved.
> Update data saving

- task-launcher/src/tasks/math/trials/sliderStimulus.ts
- task-launcher/src/tasks/roar-inference/trials/afcInference.ts
- task-launcher/src/tasks/shared/helpers/index.ts
- task-launcher/src/tasks/shared/helpers/mapDistractorsToString.ts
- task-launcher/src/tasks/shared/helpers/setSentryContext.ts
- task-launcher/src/tasks/shared/trials/afcStimulus.ts
- task-launcher/types/index.d.ts
This PR adds some more details to the sentry errors. Hopefully, it will help us narrow down the bug faster.
> Adding more sentry context

- task-launcher/src/tasks/matrix-reasoning/timeline.ts
This PR fixes a minor bug in the CAT functionality for matrix reasoning.
> fix CAT-related bug in matrix reasoning timeline

- task-launcher/src/tasks/memory-game/trials/stimulus.ts
During my refactor I had changed the timeout value from 10,000 to 10. I have restored it back to what it was in this PR.
> fix(): Restoring the timer to the past value of 10s

- task-launcher/src/tasks/same-different-selection/trials/heavyInstructions.ts
This PR adds a new button animation to the downward extension version of SDS.
> Update downward extension animations for SDS

- task-launcher/cypress/e2e/helpers.cy.js
- task-launcher/src/styles/abstracts/_fonts.scss
- task-launcher/src/styles/components/_buttons.scss
- task-launcher/src/tasks/shared/trials/afcStimulus.ts
> Egma Math UI updates

- task-launcher/src/tasks/memory-game/timeline.ts
Currently if the final practice trial has wrong input, we show a try again page but continue on the task. In this PR we update that to not show that if the final trial is wrong for the second round of tests. Here is the summary of the new behavior:
1. For the first round of practice trials (3 total), we provide for each trial.
2. If the final trial (3rd trial) is wrong, we start another set of 3 practice trials
3. In this second round, if the final trial answer is correct we provide the correct feedback screen. If the final trial answer is wrong we do not show the feedback screen and go straight to the test trials.
> feat(): Update the practice trial behavior of memory game

- task-launcher/src/tasks/same-different-selection/timeline.ts
- task-launcher/src/tasks/same-different-selection/trials/heavyInstructions.ts
- task-launcher/src/tasks/same-different-selection/trials/stimulus.ts
This PR addresses a few minor fit-and-finish issues with the downward extension version of SDS.
> SDS downward extension UI updates

- task-launcher/cypress/e2e/helpers.cy.js
- task-launcher/cypress/e2e/intro.cy.js
- task-launcher/cypress/e2e/vocab_test.cy.js
- task-launcher/serve/serve.js
- task-launcher/src/index.ts
- task-launcher/src/taskStore/index.ts
- task-launcher/src/tasks/intro/timeline.ts
- task-launcher/src/tasks/intro/trials/instructions.ts
- task-launcher/src/tasks/math/timeline.ts
- task-launcher/src/tasks/math/trials/sliderStimulus.ts
- task-launcher/src/tasks/matrix-reasoning/timeline.ts
- task-launcher/src/tasks/matrix-reasoning/trials/instructions.ts
- task-launcher/src/tasks/memory-game/trials/instructions.ts
- task-launcher/src/tasks/memory-game/trials/stimulus.ts
- task-launcher/src/tasks/mental-rotation/timeline.ts
- task-launcher/src/tasks/mental-rotation/trials/instructions.ts
- task-launcher/src/tasks/shared/helpers/PageStateHandler.ts
- task-launcher/src/tasks/shared/helpers/audioHandler.ts
- task-launcher/src/tasks/shared/helpers/getStimulus.ts
- task-launcher/src/tasks/shared/trials/index.ts
- task-launcher/src/tasks/shared/trials/practiceTransition.ts
- task-launcher/src/tasks/shared/trials/repeatInstructions.ts
- task-launcher/src/tasks/taskConfig.ts
- task-launcher/src/tasks/theory-of-mind/timeline.ts
- task-launcher/src/tasks/trog/timeline.ts
- task-launcher/src/tasks/vocab/timeline.ts
This PR adds a common screen in between the last practice trial and first test trial each task/block.
> Clarify distinction between practice and test trials

- task-launcher/src/taskStore/index.ts
- task-launcher/src/tasks/adult-reasoning/timeline.ts
- task-launcher/src/tasks/hearts-and-flowers/timeline.js
- task-launcher/src/tasks/hearts-and-flowers/trials/stimulus.js
- task-launcher/src/tasks/math/timeline.ts
- task-launcher/src/tasks/math/trials/sliderStimulus.ts
- task-launcher/src/tasks/matrix-reasoning/timeline.ts
- task-launcher/src/tasks/memory-game/timeline.ts
- task-launcher/src/tasks/memory-game/trials/stimulus.ts
- task-launcher/src/tasks/mental-rotation/timeline.ts
- task-launcher/src/tasks/roar-inference/trials/afcInference.ts
- task-launcher/src/tasks/same-different-selection/timeline.ts
- task-launcher/src/tasks/same-different-selection/trials/afcMatch.ts
- task-launcher/src/tasks/same-different-selection/trials/stimulus.ts
- task-launcher/src/tasks/shared/helpers/getRealTrials.ts
- task-launcher/src/tasks/shared/helpers/index.ts
- task-launcher/src/tasks/shared/helpers/recordCompletion.ts
- task-launcher/src/tasks/shared/helpers/trialSaving.ts
- task-launcher/src/tasks/shared/trials/afcStimulus.ts
- task-launcher/src/tasks/theory-of-mind/timeline.ts
- task-launcher/src/tasks/trog/timeline.ts
- task-launcher/src/tasks/vocab/timeline.ts
This PR marks the task run as complete once the user finishes or skips 80% of all test trials. The purpose of this change is to ensure that completion is still recorded even the user is disconnected after finishing most of the task.
> Early completion recording

- task-launcher/src/styles/pages/_egma-math.scss
- task-launcher/src/tasks/math/trials/sliderStimulus.ts
This PR introduces:
1. Similar style to range input for Number Line 4afc vs Number Line Slider even if the slider is disabled (tested it some for Firefox as well but it is not as similar looking as Chrome and other webkit browser).
2. Responsive button view and support for diamond layout and proper placement of key helpers
Some screenshots from the new implementation:
> Adding new styles and fixing responsiveness

- task-launcher/cypress/e2e/memory.cy.js
- task-launcher/src/tasks/memory-game/trials/stimulus.ts
- task-launcher/types/index.d.ts
This PR adds a `memoryGameAnswer` property to the `window` object so that it can be accessed in the Cypress code.
> Create cypress test for memory game

- task-launcher/src/styles/abstracts/_variables.scss
- task-launcher/src/styles/components/_buttons.scss
- task-launcher/src/styles/layout/_containers.scss
- task-launcher/src/tasks/math/helpers/config.ts
- task-launcher/src/tasks/same-different-selection/trials/stimulus.ts
This PR modifies fixes an instruction image that was not maintaining its aspect ratio.
Before:
After:
> Fix slider instruction image and SDS OK button being cut off

- task-launcher/src/index.ts
- task-launcher/src/tasks/taskSetup.ts
- task-launcher/src/utils/index.ts
- task-launcher/src/utils/logger.ts
- task-launcher/types/index.d.ts
This adds a posthog/ sentry logger to core task in a backward compatible manner. Currently it logs only data collection but can be fine tuned in the future.
> feat(308): Adding posthog/sentry logger

- task-launcher/cypress/e2e/hearts_and_flowers.cy.js
- task-launcher/src/styles/layout/_containers.scss
- task-launcher/src/styles/pages/_haf.scss
- task-launcher/src/tasks/hearts-and-flowers/trials/instructions.js
- task-launcher/src/tasks/intro/trials/instructions.ts
- task-launcher/src/tasks/same-different-selection/trials/afcMatch.ts
- task-launcher/src/tasks/taskSetup.ts
This fixes some of UI issues of HnF:
> fix(): fixing the issue with instruction screen

- task-launcher/.firebaserc
- task-launcher/firebase.json
- task-launcher/package.json
This PR sets up a new demo task link at `https://levante-tasks-demo.web.app/` under the `hs-levante-admin-dev` firebase project.
> Set up deployment for task demo link

- task-launcher/src/tasks/math/timeline.ts
- task-launcher/src/tasks/shared/helpers/prepareCat.ts
- task-launcher/src/tasks/shared/trials/afcStimulus.ts
- task-launcher/src/tasks/vocab/timeline.ts
This PR contains a few updates to the new math downward extension CAT based on QA feedback.
> Math downex CAT updates
