levante-framework/core-tasks

task-launcher/src/tasks/matrix-reasoning/timeline.js
task-launcher/src/tasks/memory-game/timeline.js
task-launcher/src/tasks/mental-rotation/timeline.js
task-launcher/src/tasks/same-different-selection/timeline.js
task-launcher/src/tasks/shared/helpers/fetchAndParseCorpus.js
task-launcher/src/tasks/shared/helpers/getStimulusCount.js
task-launcher/src/tasks/shared/trials/afcStimulus.js
task-launcher/src/tasks/theory-of-mind/timeline.js
task-launcher/src/tasks/trog/timeline.js

- Changing variable name maxStimulusTrials to totalTrials 
- Now accounts for all trials minus the amount of practice trials NOT given (Ex. 100 rows in corpus = 100 trials, maxPracticeTrials = 2, total trials will be 92).
- Always includes instructions. I assume that we will always want to give the amount of instructions listed in the corpus.

Fix - experiment ending early from corpus row count mismatch

---

task-launcher/src/styles/task.scss
task-launcher/src/tasks/memory-game/timeline.js
task-launcher/src/tasks/memory-game/trials/stimulus.js
task-launcher/src/tasks/shared/helpers/initTrialSaving.js

- Adding styling to stimulus trials from Figma
- Pulled out on_load code into a function
- Abstracted corsi block trials into a function that returns the trials, similar to afcStimulus.
- Updated data saved to Firestore. No longer saving save_trial flag and internal node id from jsPsych.

Adding styling from Figma, pulling out code, updating data saved to db

---

task-launcher/README.md
task-launcher/serve/serve.js
task-launcher/src/tasks/shared/helpers/fetchAndParseCorpus.js
task-launcher/src/tasks/shared/helpers/initConfig.js
task-launcher/src/tasks/shared/helpers/randomizeStimulusBlocks.js
task-launcher/src/tasks/shared/trials/afcStimulus.js
task-launcher/src/tasks/trog/timeline.js
task-launcher/src/tasks/trog/trials/instructions.js

Added parameter storeId.  When it is set, corpus and itemId fields will be added to the trial data that is saved to the database.
fetchAndParseCorpus.js: Fixed the reading of the corpus into stimulusData, preserving the original implementation of all trials going into the same structure.  The corpus used for roar-syntax will now set trial_type to stimulus for all items, so that they are randomly shuffled as one block.  Designations such as noun, verb, etc have been moved to the notes.   The trog-item-bank will continue to be shuffled only within each group of 4 items.

Add storeId parameter. Fix corpus shuffling when sequentialTrials=false

---

task-launcher/src/tasks/hearts-and-flowers/timeline.js
task-launcher/src/tasks/hearts-and-flowers/trials/stimulus.js

correctPracticeTrial value is read from admin config defined here (as of now it's 2, 2, and 3 for Hearts, Flowers, and Mixed practice blocks respectively): https://github.com/levante-framework/core-tasks/blob/044690ebfd37b6d405a233ceeb9aa13f32fb10bf/task-launcher/src/tasks/hearts-and-flowers/timeline.js#L54-L85

HaF: implement practice trial shortcut

---

task-launcher/src/tasks/hearts-and-flowers/timeline.js
task-launcher/src/tasks/hearts-and-flowers/trials/practice.js

When hitting the "winning-streak" on practice blocks (as of now it is 3 for mixed stimuli practice and 2 for the non-mixed)
We end the practice block nested timeline early via callbacks from the stimulus trial.
Problem: we skip the last feedback trial.
This makes sure this last feedback trial is shown before we exit the nested timeline early.

HaF: delay exiting the nested practice timeline to its feedback trial

---

task-launcher/src/styles/components/_buttons.scss
task-launcher/src/tasks/math/trials/sliderStimulus.js
task-launcher/src/tasks/shared/helpers/audioHandler.ts
task-launcher/src/tasks/shared/helpers/index.js
task-launcher/src/tasks/shared/helpers/replayAudio.js
task-launcher/src/tasks/shared/trials/afcStimulus.js

This PR addresses the following:
1. Disables the replay button when the initial stimulus audio is playing
2. Disables the replay button when the replay button is played and audio is playing
3. Centralizes the audio logic into a singleton so that audios don't overlap
4. Update the replay button styles to show that the button is disabled

Adding a way to disable the replay button for the initial stimulus time

---

task-launcher/src/tasks/shared/helpers/audioHandler.ts
task-launcher/src/tasks/shared/helpers/replayAudio.js
task-launcher/src/tasks/shared/trials/afcStimulus.js

I tried to make the PageAudioHandler a singleton so that only 1 audio plays at a given time but it looks like that may not be possible as of now. So this PR essentially restores the previous behavior of audio overlap between feedback and replay button. However, we are still keeping the behavior of the replay button being disabled while the audio instruction is being played. Here are my two future solutions:
1. Move out the audio stimulus from `jsPsychAudioMultiResponse` and handle the entire audio on our end. (Gives us the most options)
2. Disable the feedback buttons while the audio instructions are playing and disable replay button while the feedback audio is playing (not ideal and will lead to some bad UX)

Consolidating afcstimulus audio to page audio handler

---

task-launcher/src/tasks/hearts-and-flowers/timeline.js
task-launcher/src/tasks/hearts-and-flowers/trials/practice.js

**Previous behavior (Practice):**
Incorrect response > show incorrect response > stay in the same trial with incorrect message > disable incorrect button (loop) > click correct response > go to next trial (good job screen is not shown in this case)
Correct response > good job screen > next trial
Additionally we show replay button in the incorrect and correct screen
**New behavior (Practice):**
Incorrect response > no replay button but the incorrect audio plays > loops back to the start of the instruction > correct response > show good job screen > next trial
Correct response > good job screen > next trial
No replay button shown since the screen are timed and the trial ends the moment audio stops and goes back to the instruction page (replay button is shown there)

fix(): fixing the trial loops of haf

---

task-launcher/src/tasks/shared/trials/afcStimulus.ts

I think this fixes the issue where the answer for math trials was always being saved as 7/8. For some reason taskStore().target (which was previously being saved as the answer in the data) is 7/8 for all math trials, but the target value stored in layoutConfig is accurate. It might be good to eventually find out why taskStore doesn't have the right value, but this should fix the problem for now.

Fix math answer saving

---

task-launcher/src/tasks/math/trials/sliderStimulus.ts
task-launcher/src/tasks/same-different-selection/trials/afcMatch.ts
task-launcher/src/tasks/same-different-selection/trials/stimulus.ts
task-launcher/src/tasks/shared/trials/afcStimulus.ts

Response times were not being saved for some trials - as far as I can tell from looking at the jsPsych data object, these were the number line trials with buttons and the matching and test-dimensions phases of SDS. In this PR I manually calculated response times for these trials and added them to jsPsych.data (I saw this was also being done for keyboard responses in afcStimulus). I also noticed that RTs are not saved for practice trials - I'm not sure if we want those, but I could save them if that would be good!

Fix some response times not being saved in data

---

task-launcher/cypress.config.js
task-launcher/cypress/e2e/helpers.cy.js
task-launcher/cypress/e2e/math.cy.js
task-launcher/cypress/e2e/matrix_reasoning.cy.js
task-launcher/cypress/e2e/mental_rotation_test.cy.js
task-launcher/cypress/e2e/theory_of_mind.cy.js
task-launcher/cypress/e2e/trog_test.cy.js
task-launcher/cypress/e2e/vocab_test.cy.js
task-launcher/cypress/support/e2e.js
task-launcher/src/tasks/math/trials/sliderStimulus.ts
task-launcher/src/tasks/shared/trials/afcStimulus.ts

This PR implements cypress tests for matrix reasoning, theory of mind, and math.

Cypress tests for remaining afcStimulus tasks

---

task-launcher/cypress/e2e/hearts_and_flowers.cy.js

Adds a cypress test for hearts and flowers. It should only pass if each of the three main phases (flowers only, hearts only, and both) have at least one trial.

Hearts and flowers cypress test

---

task-launcher/src/tasks/intro/trials/instructions.ts

Adds a simple screen with instructions on how to use the keyboard to answer questions (the English text is "If you want to use your keyboard to answer a question, press the arrow key shown next to your choice."). It might be good if someone with a tablet could test to make sure the screen is not showing up for them. 
I also think it would be good to eventually replace the owl with a graphic that has an image of the arrow keys and example buttons with arrows next to them

Adds keyboard instruction screen

---

task-launcher/src/styles/abstracts/_fonts.scss
task-launcher/src/styles/abstracts/_variables.scss
task-launcher/src/styles/layout/_containers.scss
task-launcher/src/tasks/intro/trials/instructions.ts
task-launcher/src/tasks/matrix-reasoning/helpers/config.ts
task-launcher/src/tasks/matrix-reasoning/trials/instructions.ts
task-launcher/src/tasks/shared/trials/afcStimulus.ts
task-launcher/src/tasks/theory-of-mind/helpers/config.ts

The goal of this PR is to prevent the bottom buttons from leaving the screen, which was happening for matrix reasoning and TOM. I applied the `instruction-small` class to these tasks and also made each of the size variables for the `image` button class slightly smaller, which changes the size of the big stimulus images since they were previously set to 3x the size of the buttons. As far as I know `image` is currently only used for the buttons in these two tasks, so buttons in other tasks shouldn't be affected. I also slightly decreased the font size used for `instruction-small` and gave it min and max values.

Update CSS to prevent content from leaving screen

---

task-launcher/src/styles/layout/_video-containers.scss
task-launcher/src/tasks/memory-game/trials/instructions.ts

This PR addresses the comment from Germany that the OK button is leaving the screen during the instruction trials. I shrank the video size to create more room, which seems to solve the problem for most screen sizes. 
There was another comment about images briefly flashing on the screen before the instruction video. Because this stops happening after the task is reloaded a few times, I think it might be related to how the assets are loading (although I tried preloading the assets for memory game and it did not fix the issue). For now I added a short gap between instruction screens, which I think makes them easier to read and makes the image flickering less distracting when it does happen.

Fix memory game UI

---

task-launcher/src/styles/components/_buttons.scss
task-launcher/src/tasks/hearts-and-flowers/trials/practice.js

This PR fixes a bug in hearts and flowers caused by the user clicking the buttons during the incorrect feedback screen (for some reason this was causing the task to skip additional trials while the screen was still showing). I disabled the buttons and all key presses during feedback trials to prevent this, and also added the pulse animation back into the H&F button class.

Define pulse animation and disable buttons/key presses

---

task-launcher/src/tasks/shared/trials/afcStimulus.ts

This PR fixes an audio overlap issue that was happening in afcStimulus.ts practice trials - the prompt audio was carrying over to the next trial because it wasn't stopped (the practice audio was being stopped instead). The prompt audio now stops before the practice audio starts (so that clicking an answer interrupts the audio, like in test trials).

Fix audio overlap in matrix practice trials

---

task-launcher/serve/serve.js
task-launcher/src/taskStore/index.ts
task-launcher/src/tasks/shared/helpers/config.ts
task-launcher/src/tasks/shared/helpers/prepareCat.ts
task-launcher/src/tasks/taskSetup.ts

This PR adds a url parameter to set the starting theta value, which can be used to start out younger kids with easier items for matrix reasoning and mental rotation. For right now, I also limited the difficulty of the start items so that they are less than the starting theta (otherwise hard items could still show up in the block of 5 random starting items, which I forgot about during the LEVANTE team meeting). 
Another approach could be to create the option to remove the starting items entirely. I'm also not sure if we always want to limit the starting item difficulty - for older kids we might want to allow items that are higher than the starting theta. @mcfrank let me know if you have any thoughts about what to do with the starting block for younger kids. Thanks!

CAT updates for downward extension

---

task-launcher/src/taskStore/index.ts
task-launcher/src/tasks/math/timeline.ts
task-launcher/src/tasks/math/trials/sliderStimulus.ts
task-launcher/src/tasks/shared/helpers/handlePracticeButtons.ts
task-launcher/src/tasks/shared/helpers/index.ts
task-launcher/src/tasks/shared/helpers/setSkipCurrentBlock.ts
task-launcher/src/tasks/shared/trials/afcStimulus.ts
task-launcher/src/tasks/shared/trials/feedback.ts

This PR allows practice trials to be added to the slider block, which currently repeat once as a block if they are answered incorrectly. It also prevents the pause that occurs when the task skips to the next block.

Add practice trials to math and shorten gap between blocks

---

task-launcher/src/tasks/same-different-selection/trials/afcMatch.ts

This PR fixes the way that higher-dimension matching trials are scored. Because the item names in the corpus leave out the number or color dimension if it has the default value (for example,  "med-red-square" rather than "med-red-square-1-white") I added those values back in the task code before they are scored. Additionally, a selection is now flagged as a repeat only if the same two cards were picked in one previous selection (rather than across multiple previous selections).

Fix scoring of higher-dimension matching trials in same different selection

---

task-launcher/src/tasks/math/helpers/config.ts
task-launcher/src/tasks/math/timeline.ts
task-launcher/src/tasks/memory-game/timeline.ts
task-launcher/src/tasks/shared/trials/feedback.ts

This PR allows instruction trials in the math corpus to include images, which is necessary for the slider block instruction trial. It also creates the option to not show the prompt at the bottom of the feedback screen.

Update math feedback and instructions

---

task-launcher/src/index.ts
task-launcher/src/taskStore/index.ts
task-launcher/src/tasks/shared/trials/finishExperiment.ts
task-launcher/src/tasks/shared/trials/taskFinished.ts

The goal of this PR is to standardize the user's experience at the end of the task. Currently, the user is sometimes returned to the dashboard before they press the 'Exit' button on the end screen (particularly when they error/time out of a task), and sometimes only after they press it. This PR requires that the task does not end until the button is pressed, regardless of how the task is completed.

Require button press or keydown on end screen to finish task

---

task-launcher/src/styles/pages/_roar-inference.scss
task-launcher/src/tasks/roar-inference/helpers/config.ts
task-launcher/src/tasks/roar-inference/trials/afcInference.ts

When the story is very very big, on very small devices they can't see the whole stimuli.
Example: 
After (I had to take it with my phone to show the scrolling bar):

Allow scrolling for Roar-Inference

---

task-launcher/src/index.ts
task-launcher/src/utils/initPageSetup.ts

This should make the overlay warnings for device type, language sensitive with some default texts. The keys of the texts would be:
general-rotate-device: For device rotation
general-device-type: For small device
We need to add them to the translations file.

fix(): Making the overlay warnings language sensitive

---

task-launcher/src/taskStore/index.ts
task-launcher/src/tasks/same-different-selection/trials/afcMatch.ts

The audio overlap between trials issue has been fixed for all other tasks by switching to `html-multi-response` and using the `PageAudioHandler` class to play audio, but for some reason using `html-multi-response` here was causing an error in the plugin code. To fix this, I left it as an `audio-multi-response` trial but with `nullAudio` as the stimulus.

Prevent SDS audio overlap between trials

---

task-launcher/src/utils/initPageSetup.ts

Adding a default way to calculate the orientation. This should fix the bug here:
https://levante-framework.sentry.io/issues/6599022203/?alert_rule_id=15684260&alert_timestamp=1746973666780&alert_type=email&environment=production&notification_uuid=0e75f140-eaf4-4202-b3cf-5f80a5ca31e1&project=4508480347832320&referrer=alert_email

fix(): Orientation Type bug

---

task-launcher/src/styles/components/_buttons.scss
task-launcher/src/styles/pages/_egma-math.scss
task-launcher/src/taskStore/index.ts
task-launcher/src/tasks/math/helpers/config.ts
task-launcher/src/tasks/math/timeline.ts
task-launcher/src/tasks/math/trials/sliderStimulus.ts
task-launcher/src/tasks/shared/helpers/getStimulus.ts
task-launcher/src/tasks/shared/helpers/setSkipCurrentBlock.ts

This PR adds a few new math trial types for younger kids and runs only block 3 of the corpus (which will contain the downward extension version of math) if `heavyInstructions` is turned on.

Math downward extension

---

task-launcher/src/tasks/same-different-selection/trials/stimulus.ts
task-launcher/src/tasks/shared/helpers/handlePracticeButtons.ts

Replaces `click` event listeners with `touchend` listeners for practice buttons, which have sometimes been unresponsive on tablets.

Look for touch rather than click events if touch screen is detected

---

task-launcher/src/index.ts
task-launcher/src/tasks/shared/trials/finishExperiment.ts
task-launcher/src/tasks/shared/trials/taskFinished.ts

This ticket adds the following events:
1. Task Launch (after loading screen is over)
2. Task Finished (task is fully completed)
3. Task Aborted (task is stopped due to user errors)

Adding a few more events to see task related status

---

task-launcher/src/index.ts
task-launcher/src/tasks/shared/helpers/getTranslations.ts

This PR switches to reading item-bank-translations.csv from the admin firebase projects (in the `levante-dashboard-dev` and `levante-dashboard-prod` buckets) rather than the road-dashboard bucket in `hs-levante-assessment-prod`.

Read item-bank-translations csv from admin firebase projects

---

task-launcher/src/taskStore/index.ts
task-launcher/src/tasks/shared/helpers/appTimer.ts
task-launcher/src/tasks/shared/helpers/getStimulus.ts

This PR adds a check for the amount of time remaining during the fixation/setup trials and ends the task if there is not enough time to show the next stimulus. This is meant to prevent the abrupt switch to the end-of-task screen while the audio file is still playing for a trial.

Prevent timeout interrupting the stimulus

---

task-launcher/src/styles/abstracts/_spacings.scss
task-launcher/src/styles/components/_buttons.scss
task-launcher/src/styles/layout/_containers.scss
task-launcher/src/tasks/math/helpers/config.ts

This PR adjusts some styling to try to address the issues that Colombia is having. I resized the mental rotation buttons based on an `adjusted-viewport` variable, and removed an unnecessary top margin from the instructions. We could try resizing everything based on `adjusted-viewport`, but I went with the minimal change that might help for now.

Styling updates

---

task-launcher/src/tasks/shared/helpers/prepareCat.ts
task-launcher/src/tasks/theory-of-mind/timeline.ts

This PR fixes a bug that was caused by block numbers not being in order in one of the theory of mind retest corpora - the assets were being preloaded out of order.

Colombia bug fixes

---

task-launcher/src/tasks/math/timeline.ts

This PR fixes a bug where completion was being recorded for the math CAT early, so a user could exit out after a few trials and it would show as completed. The wrong trial counter variable was being updated in the math timeline. Closes #380

Fix math ending early

---

task-launcher/src/index.ts
task-launcher/src/tasks/shared/helpers/getAssetsPerTask.ts

This PR fixes a bug where the assets-per-task.json file was always being read from the dev bucket, even when running on prod.

Fix assets-per-task.json always being read from dev
